# coding=utf8
# the above tag defines encoding for this document and is for Python 2.x compatibility

import re
import os

DIR = os.path.dirname(os.path.abspath(__file__))


test_str = (
    "UE工具开发参考资料\n"
    "-Ocarmihe\n"
    "1. 开发规范\n"
    "	1.1. 光子UE4项目C++编码规范\n"
    "http://km.oa.com/group/GZSGtechCT/articles/show/328550\n"
    "	1.2. Epic Game代码规范\n"
    "https://docs.unrealengine.com/zh-CN/ProductionPipelines/DevelopmentSetup/CodingStandard/index.html\n"
    "	1.3. Unreal style guide\n"
    "https://github.com/Allar/ue5-style-guide\n"
    "关于资产命名、蓝图相关代码结构规范的检查\n"
    "	1.4 MarketPlace Guidelines\n"
    "https://www.unrealengine.com/en-US/marketplace-guidelines\n"
    "Unreal商店产品发行级内容标准\n\n"
    "2. Extending Unreal Engine \n"
    "	2.1. Development of asset editor in Unreal Engine.\n"
    "https://easycomplex-tech.com/blog/Unreal-AssetEditor/\n"
    "https://easycomplex-tech.com/cnblog/Unreal-AssetEditor/\n"
    "比较详细的编辑器框架介绍，从如何创建一个资产到如何给资产编辑器添加各种常用模块\n"
    "（如节点图表、预览窗口），但是没有完整代码。\n\n"
    "	2.2. FMX 2017: Extending Unreal Engine 4 with Plug-ins (Master Class)\n"
    "PPT:https://www.slideshare.net/GerkeMaxPreussner/fmx-2017-extending-unreal-engine-4-with-plugins-master-class\n"
    "      视频:https://learn.unrealengine.com/course/2504894?r=False&ts=637528445757941424\n"
    "官方分享:主要介绍了创建插件、Asset、AssetFactory、Module的内容。可略看\n\n"
    "	2.3. Epic参考文档&链接\n"
    "		2.3.1. Unreal Online Learning\n"
    "https://learn.unrealengine.com/home/dashboard\n"
    "Uneal引擎官方在线学习平台链接\n"
    "		2.3.2. 大钊:C++进阶之路\n"
    "[第三方内容]\n"
    "		2.3.3. Slate \n"
    "https://docs.unrealengine.com/zh-CN/ProgrammingAndScripting/Slate/Architecture/index.html\n\n"
    "	2.4. C++ Extending the Editor | Live Training | Unreal Engine\n"
    "https://www.youtube.com/watch?v=zg_VstBxDi8&t=4213s\n"
    "也是UE4工具开发参考，但是2015年时间比较久了。\n\n"
    "	2.5. 工具开发相关博客\n"
    "		2.5.1. JAN_WLOSOK:Editor plugins in UE4 #3 – Toolbar button	\n"
    "http://wlosok.cz\n"
    "介绍了一些建议插件模板和代码示例,给引擎添加快捷按钮\n"
    "(如MenuButton\\Toolbar Button\\)\n"
    "		2.5.2. [UE4] Eric Zhang：Make tools in unreal4\n"
    "https://lxjk.github.io/2019/10/01/How-to-Make-Tools-in-U-E.html\n"
    "https://github.com/lxjk/ToolExample \n"
    "比较详细的一篇工具开发博客，内容详实包含代码，同时还介绍了EditorMode（主要		用于Level关卡中的编辑功能）的开发\n"
    "		2.5.3. YakSue:总结了很多编辑器扩展和节点图表和示例代码，很好的参考；\n"
    "https://blog.csdn.net/u013412391/category_10839272.html\n"
    "https://blog.csdn.net/u013412391/category_10839293.html\n"
    "		2.5.4. HHH:关于PreviewScene预览窗口的补充部分介绍得比较详细\n"
    "https://blog.csdn.net/github_38111866/category_8894643.html\n"
    "		2.5.5. 浮光:UE4编辑器扩展\n"
    "https://zhuanlan.zhihu.com/p/258968098\n"
    "对几个基类的概念和代码关系分析(UObject\\AssetAction\\Factory)\n"
    "		2.5.6. [UE4]NeilWang:Editor Extention and Programming\n"
    "https://dawnarc.com/2018/12/ue4editor-extention-and-programming/\n"
    "		2.5.7. Writing a custom asset editor FOR UNREAL ENGINE 4 - PART 1\n"
    "http://cairansteverink.nl/cairansteverink/blog/writing-a-custom-asset-editor-for-unreal-engine-4-part-1/\n"
    "创建一个Asset和空Editor，有完整代码参考；\n"
    "		2.5.8. Factory\n"
    "https://blog.csdn.net/u013412391/article/details/107646900\n"
    "		2.5.9. PreviewScene\n"
    "https://blog.csdn.net/github_38111866/article/details/105773368\n"
    "https://blog.csdn.net/u013412391/article/details/109258860?utm_medium=distribute.pc_relevant.none-task-blog-baidujs_title-0&spm=1001.2101.3001.4242\n"
    "为项目添加预览窗口\n"
    "		2.5.10. IDetailCustom\n"
    "https://zhuanlan.zhihu.com/p/135316945\n"
    "定制自定义属性样式，在开发Detail面板时比较常用的功能\n"
    "		2.5.11. Adding New Asset Types to UE4\n"
    "https://gmpreussner.com/reference/adding-new-asset-types-to-ue4\n"
    "自定义Asset资产的显示风格和目录\n"
    "		2.5.12. K2Node\n"
    "https://blog.csdn.net/u013507300/article/details/109165560\n"
    "如何自定义Pin\n"
    "	2.6. 参考项目、github代码仓库\n"
    "		2.6.1. 插件中间件开发Mutable：\n"
    "https://mutable.games/#page\n"
    "Doc:Mutable for UnrealEngine4\n"
    "https://work.anticto.com/w/mutable/unreal-engine-4/\n"
    "Node Reference:\n"
    "https://work.anticto.com/w/mutable/unreal-engine-4/user-documentation/nodes/\n"
    "		2.6.2. SnowDrop节点编辑器Ubisoft：https://www.smartrecruiters.com/Ubisoft2/743999754125139-senior-system-programmer-snowdrop-?trid=4d32c519-f437-439a-ab4f-b3953c48d5c1\n"
    "		2.6.3. Animated Texture with GIF Importer\n"
    "https://github.com/neil3d/UnrealAnimatedTexturePlugin\n"
    "Runtime\\Editor 模块区分\n"
    "		2.6.4. Nodes-Graph Develop\n"
    "https://github.com/flashpoint493/YetAnotherGraphPlugin\n"
    "https://github.com/Eragon-Brisingr/XD_GraphEditor_Template\n"
    "节点图表案例\n\n\n\n"
    "3. Unreal Shader&Material\n"
    "	3.1. Decal BP API\n"
    "https://docs.unrealengine.com/en-US/Resources/ContentExamples/Decals/index.html\n"
    "	3.2. Dynamic Material Instance C++ Api\n"
    "https://docs.unrealengine.com/en-US/API/Runtime/Engine/Materials/UMaterialInstanceDynamic/index.html\n"
    "动态材质示例\n"
    "	3.3. Dynamic Material Instance  BP Api\n"
    "https://docs.unrealengine.com/en-US/BlueprintAPI/Rendering/Material/CreateDynamicMaterialInstance/index.html\n"
    "	3.4. Programmatically Create Material \n"
    "https://isaratech.com/save-a-procedurally-generated-texture-as-a-new-asset/\n"
    "https://isaratech.com/ue4-programmatically-create-a-new-material-and-inner-nodes/\n"
    "https://zhuanlan.zhihu.com/p/45171840\n"
    "https://blog.csdn.net/mrbaolong/article/details/112548477\n"
    "程序化创建Material资产及其内部节点逻辑；用于基于UE4 Material Function批量制作新shader；\n"
    "	3.5. Material Function library\n"
    "https://docs.unrealengine.com/en-US/RenderingAndGraphics/Materials/Functions/Reference/index.html\n\n"
    "4. Unreal4 Build Tools\n"
    "	4.1. UBT\n"
    "https://docs.unrealengine.com/en-US/ProductionPipelines/BuildTools/index.html\n"
    "	4.2. Blueprint Compiler Internals I\n"
    "https://ikrima.dev/ue4guide/engine-programming/blueprints/bp-compiler-internals-1/\n"
    "	4.3. Blueprint Compiler Overview\n"
    "https://docs.unrealengine.com/en-US/ProgrammingAndScripting/Blueprints/TechnicalGuide/Compiler/index.html\n"
    "	4.4. FCK\n"
    "https://blog.csdn.net/Neil3D/article/details/103221164 \n"
    "https://www.ue4community.wiki/legacy/create-custom-k2-node-for-blueprint-zwuncdkq\n"
    "https://github.com/neil3d/UnrealCookBook/tree/master/MyBlueprintNode\n\n"
    "5. Character Customizer\n"
    "	5.1. https://www.unrealengine.com/marketplace/en-US/product/character-customizer\n"
    "	5.2. 游戏角色实用技术杂谈(06/2021) v0.1 beta\n"
    "https://zhuanlan.zhihu.com/p/389079538\n"
    "	5.3. 基于骨骼的捏脸系统\n"
    "https://buaaccj.github.io/2019/09/30/unreal%E4%B8%AD%E7%9A%84%E6%8D%8F%E8%84%B8%E7%B3%BB%E7%BB%9F/ \n"
    "	5.4. 参考项目\n"
    "		5.4.1. Character Editor\n"
    "https://www.unrealengine.com/marketplace/en-US/product/character-editor\n"
    "		5.4.2. Character Customization\n"
    "https://www.youtube.com/watch?v=5kjne-XPlUE\n"
    "		5.4.3. Character Customizer v2 for UE4\n"
    "https://www.youtube.com/watch?v=SzBmwgHvpK4、\n"
    "	5.5. 模块化换装:https://blog.csdn.net/luomogenhaoqi/article/details/88638068\n\n"
    "6. Control Rig\n"
    "	6.1. Animating with Control Rig\n"
    "https://www.youtube.com/watch?v=UyCziUcnqxM&t=5s\n"
    "https://www.youtube.com/watch?v=UyCziUcnqxM&t=8042s\n\n"
    "7. UE4妆容系统\n"
    "	7.1. render target\n"
    "		7.1.1. render targets\n"
    "https://docs.unrealengine.com/zh-CN/RenderingAndGraphics/RenderTargets/index.html\n"
    "		7.1.2. Creating Textures Using Blueprints and Render Targets\n"
    "https://docs.unrealengine.com/zh-CN/RenderingAndGraphics/RenderTargets/BlueprintRenderTargets/HowTo/CreatingTextures/index.html\n"
    "		7.1.3. Unreal Engine 4 Tutorial: Painting With Render Targets\n"
    "https://www.raywenderlich.com/5246-unreal-engine-4-tutorial-painting-with-render-targets\n"
    "		7.1.4. Fast Render Target Rendering in Unreal Engine 4\n"
    "https://www.froyok.fr/blog/2020-06-render-target-performances/page.html\n"
    "		7.1.5. Blueprint Drawing to Render Targets Overview | Live Training | Unreal Engine\n"
    "https://www.youtube.com/watch?v=1Z-V1Buk6z8\n"
    "		7.1.6. Introduction to Render Targets - Unreal Engine 4 Tech Art S03E02\n"
    "https://www.youtube.com/watch?v=LXduG19JFWg\n"
    "		7.1.7. UE4 Importing and Exporting Render Targets (Save and Load) using Blueprints\n"
    "https://www.youtube.com/watch?v=bb_yw5Cvs6k\n\n"
    "8. Skeleton Animation\n"
    "	8.1. rbf\n"
    "原理：http://www.marcuskrautwurst.com/2017/12/rbf-node.html\n"
    "https://gumroad.com/jamesvsnowden/p/wtf-is-rbf\n"
    "实现例子：https://www.chadvernon.com/blog/rbf/\n"
    "https://vimeo.com/196583536\n"
    "	8.2. PoseDrive Animation\n"
    "https://docs.unrealengine.com/en-US/AnimatingObjects/SkeletalMeshAnimation/AnimPose/PoseDriverNode/index.html\n"
    "（maya) http://www.braverabbit.com/braverabbit/tools/weightdriver/#1575623493759-e346cecf-75c6330d-2f0fb24f-beac\n"
    "	8.3. 捏脸系统Git\n"
    "https://km.woa.com/search?q=%E6%8D%8F%E8%84%B8%E7%B3%BB%E7%BB%9F\n"
    "https://km.woa.com/group/29321/articles/show/450545?kmref=search&from_page=1&no=1\n"
    "	8.4. 天刀角色整形美容技术揭秘\n"
    "https://km.woa.com/group/1556/articles/show/224768?kmref=search&from_page=1&no=10\n"
    "	8.5. PSD\n"
    "		8.5.1. 原理\n"
    "https://docs.google.com/presentation/d/1z41rXP8EJiWXmqhNKHkNqI9patuaI352f1tlqfBOO9c/htmlpresent\n"
    "		8.5.2. Maya - PSD应用效果参考：\n"
    "https://www.youtube.com/watch?v=mxlRMAs_HJU\n"
    "	8.6. Advanced Locomotion System V4\n"
    "https://www.unrealengine.com/marketplace/zh-CN/product/advanced-locomotion-system-v1\n"
    "	8.7. (Tutorial) Unreal Engine Mesh Morpher - Create Morph Target From Mesh (Morph Through Meta Humans\n"
    "https://www.youtube.com/watch?v=kCpdVm2bWEI\n\n\n"
    "9. UE4动画蓝图节点开发\n"
    "	9.1. Create Custom Anim Node\n"
    "https://www.unrealengine.com/zh-CN/blog/creating-custom-animation-nodes?lang=zh-CN\\\n"
    "	9.2. 动画节点技术指南\n"
    "https://docs.unrealengine.com/4.26/zh-CN/AnimatingObjects/AnimationNodeTechnicalGuide/\n"
    "	9.3. AnimNode\n"
    "https://dawnarc.com/2019/01/ue4transform-skeletal-bone-in-c-/\n"
    "	9.4. AnimNode\n"
    "https://blog.csdn.net/weixin_30840573/article/details/99304022 \n"
    "https://forums.unrealengine.com/t/a-new-community-hosted-unreal-engine-wiki/141494\n\n"
    "10. Debug\n"
    "World Context\n"
    "https://answers.unrealengine.com/questions/480818/how-to-use-getworld-from-uobject-correctly.html\n\n"
    "11. Rendering\n"
    "UberBake System\n"
    "https://cs.dartmouth.edu/~wjarosz/publications/seyb20uberbake.html\n"
    "Unreal Rendering Part\n"
    "https://medium.com/@lordned/unreal-engine-4-rendering-overview-part-1-c47f2da65346\n\n"
    "12. MateHuman Reference\n"
    "	12.1. 官方文档\n"
    "https://docs.unrealengine.com/en-US/Resources/Showcases/MetaHumans/index.html\n"
    "	12.2. Retargeting Animations onto a MetaHuman\n"
    "https://docs.unrealengine.com/en-US/Resources/Showcases/MetaHumans/RetargetingAnimationsOntoMetaHumans/index.html\n"
    "	12.3. SkeletaMeshAnimation\n"
    "https://docs.unrealengine.com/en-US/AnimatingObjects/SkeletalMeshAnimation/index.html \n"
    "	12.4. Control Rig：Curve Driven Animation\n"
    "https://docs.unrealengine.com/en-US/AnimatingObjects/SkeletalMeshAnimation/AnimHowTo/CurveDrivenAnimation/index.html\n\n"
    "	12.5. Animation How To's\n"
    "https://docs.unrealengine.com/en-US/AnimatingObjects/SkeletalMeshAnimation/AnimHowTo/index.html\n"
    "视频补充：\n"
    "	12.6. Using Control Rig in Unreal Engine\n"
    "https://www.youtube.com/watch?v=y2WzNvJZk0E&t=382s \n"
    "	12.7. matehuman资产与动画移植倒自定义角色上：\n"
    "https://www.youtube.com/watch?v=qpIAgFAGfuU\n"
    "https://www.youtube.com/watch?v=h5W9noO_1QY\n"
    "https://www.youtube.com/watch?v=X3QILs0tkYs\n"
    "	12.8. (Tutorial) Unreal Engine Mesh Morpher - Create Morph Target From Mesh (Morph Through Meta Humans)\n"
    "https://www.youtube.com/watch?v=_dXJJt7_p6g\n"
    "	12.9. Physics\n"
    "https://documentation.help/NVIDIA-PhysX-SDK-Guide/RigidDynamics.html\n"
    "	12.10. Unreal Optimization\n"
    "https://software.intel.com/content/www/us/en/develop/articles/unreal-engine-4-optimization-tutorial-part-3.html\n\n"
    "13. Control Rig\n"
    "	13.1. Animating with Control Rig in 4.26 | Inside Unreal\n"
    "https://www.youtube.com/watch?v=UyCziUcnqxM&t=7025s\n"
    "	13.2. Using Control Rig in Unreal Engine\n"
    "https://www.youtube.com/watch?v=y2WzNvJZk0E&t=35s\n"
    "	13.3. Using the MetaHuman Facial Rig in UE | Unreal Engine\n"
    "https://www.youtube.com/watch?v=GEpH3o44_58 \n"
    "	13.4. Control Rig Tutorial - Part 01 - Animation In Unreal Engine 4 | Sonali Singh\n"
    "https://www.youtube.com/watch?v=nblqNp7XoWU&list=PLeW1HEiOW3AKGYm5bx9iGtN1vIy_2San9 \n"
    "	13.5. Enhancing Animation with Control Rig | GDC 2019 | Unreal Engine\n"
    "https://www.youtube.com/watch?v=TYSdxW2WHcI&t=306s \n\n\n"
)


def handle_match(match):
    header = match.group(2)
    count = header.count(".")
    return match.group(1) + "#" * count

regex = r"(^|\t)+((\d|\.)+)"
output_str = re.sub(regex, handle_match, test_str, flags=re.MULTILINE)
with open(os.path.join(DIR, "output.txt"), "w", encoding="utf-8") as wf:
    wf.write(output_str)
