['_MutableMapping__marker', '__abstractmethods__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__setitem__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_construct', '_ftrack_attribute_storage', '_ignore_data_keys', '_inflated', '_populate_unset_scalar_attributes', '_reconstruct', 'attributes', 'clear', 'create_thumbnail', 'default_projections', 'entity_type', 'get', 'items', 'keys', 'logger', 'merge', 'pop', 'popitem', 'primary_key_attributes', 'reset_api_key', 'send_invite', 'session', 'setdefault', 'start_timer', 'stop_timer', 'update', 'values']
{
    "last_name": "<class 'str'>",
    "thumbnail": "<class 'NoneType'>",
    "id": "<class 'str'>",
    "timelogs": "<class 'ftrack_api.collection.Collection'>",
    "is_otp_enabled": "<class 'bool'>",
    "custom_attributes": "<class 'ftrack_api.collection.KeyValueMappedCollectionProxy'>",
    "require_details_update": "<class 'bool'>",
    "is_totp_enabled": "<class 'bool'>",
    "metadata": "<class 'ftrack_api.collection.KeyValueMappedCollectionProxy'>",
    "username": "<class 'str'>",
    "user_security_roles": "<class 'ftrack_api.collection.Collection'>",
    "thumbnail_id": "<class 'NoneType'>",
    "is_active": "<class 'bool'>",
    "first_name": "<class 'str'>",
    "dashboard_resources": "<class 'ftrack_api.collection.Collection'>",
    "appointments": "<class 'ftrack_api.collection.Collection'>",
    "email": "<class 'str'>",
    "memberships": "<class 'ftrack_api.collection.Collection'>",
    "assignments": "<class 'ftrack_api.collection.Collection'>",
    "thumbnail_url": "<class 'dict'>",
    "allocations": "<class 'ftrack_api.collection.Collection'>",
    "resource_type": "<class 'str'>"
}