# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\MayaTecent\MayaScript\model\outline\outline.ui'
#
# Created: Mon Dec 23 15:45:31 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(442, 234)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Gen_Profile_BTN = QtWidgets.QPushButton(Form)
        self.Gen_Profile_BTN.setObjectName("Gen_Profile_BTN")
        self.verticalLayout.addWidget(self.Gen_Profile_BTN)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Profile_LE = QtWidgets.QLineEdit(Form)
        self.Profile_LE.setObjectName("Profile_LE")
        self.horizontalLayout.addWidget(self.Profile_LE)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Adjust_Layout = QtWidgets.QWidget(Form)
        self.Adjust_Layout.setObjectName("Adjust_Layout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Adjust_Layout)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.Adjust_Layout)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.U_SP = QtWidgets.QSpinBox(self.Adjust_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U_SP.sizePolicy().hasHeightForWidth())
        self.U_SP.setSizePolicy(sizePolicy)
        self.U_SP.setMinimum(1)
        self.U_SP.setObjectName("U_SP")
        self.horizontalLayout_5.addWidget(self.U_SP)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.Adjust_Layout)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.V_SP = QtWidgets.QSpinBox(self.Adjust_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.V_SP.sizePolicy().hasHeightForWidth())
        self.V_SP.setSizePolicy(sizePolicy)
        self.V_SP.setMinimum(1)
        self.V_SP.setObjectName("V_SP")
        self.horizontalLayout_4.addWidget(self.V_SP)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.Adjust_Layout)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.Thickness_SP = QtWidgets.QDoubleSpinBox(self.Adjust_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Thickness_SP.sizePolicy().hasHeightForWidth())
        self.Thickness_SP.setSizePolicy(sizePolicy)
        self.Thickness_SP.setMinimum(-999.0)
        self.Thickness_SP.setMaximum(999.0)
        self.Thickness_SP.setSingleStep(0.01)
        self.Thickness_SP.setProperty("value", 1.0)
        self.Thickness_SP.setObjectName("Thickness_SP")
        self.horizontalLayout_3.addWidget(self.Thickness_SP)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.Complete_BTN = QtWidgets.QPushButton(self.Adjust_Layout)
        self.Complete_BTN.setObjectName("Complete_BTN")
        self.verticalLayout_2.addWidget(self.Complete_BTN)
        self.verticalLayout.addWidget(self.Adjust_Layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "挤出轮廓", None, -1))
        self.Gen_Profile_BTN.setText(QtWidgets.QApplication.translate("Form", "生成轮廓", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "轮廓组", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "U向分段", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "V向分段", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "厚度调整", None, -1))
        self.Complete_BTN.setText(QtWidgets.QApplication.translate("Form", "完成调整", None, -1))

